{
    // not used except for preview
    tokens = [
        WHITESPACE     =   'regexp:[ \t\v\a]+'
        NL             =   'regexp:\r?\n'
        NUMBER         =   'regexp:[0-9]+(\.[0-9]*)?|(\.[0-9]+)'
        KEYWORD        =   "regexp:\(exact\)|fun|disable-next-line|disable-line|disable|enable|\(key\)|private|protected|public"
        TEXT           =   'zzz'
        NAME           =   'regexp:[A-Za-z0-9_][A-Za-z0-9_.*\-]*'
        CODE           =   'regexp:`[A-Za-z0-9_][A-Za-z0-9_.*\-]*`'
        STRING         =   'regexp:("[^"]*")|(\'[^\']*\')'
        DASHES         =   'regexp:---+'
        TAG            =   'regexp:@alias|@async|@cast|@class|@deprecated|@diagnostic|@enum|@field|@generic|@meta|@module|@nodiscard|@overload|@operator|@package|@param|@private|@protected|@return|@see|@source|@type|@vararg|@version'
        SYMBOL         =   "regexp:[<>|,:.\[\]()*?]|\.\.\."
    ]

    generate=[tokenAccessors="no"]

    parserClass="net.internetisalie.lunar.luacats.lang.parser.LuaCatsParser"
    parserImports=[]

    extends="net.internetisalie.lunar.luacats.lang.psi.LuaCatsBaseElement"

    tokenTypeClass="net.internetisalie.lunar.luacats.lang.lexer.LuaCatsElementType"

    elementTypeHolderClass="net.internetisalie.lunar.luacats.lang.psi.LuaCatsElementTypes"
    elementTypeClass="net.internetisalie.lunar.luacats.lang.psi.LuaCatsElementType"

    psiClassPrefix='LuaCats'
    psiPackage='net.internetisalie.lunar.luacats.lang.psi'
    psiImplPackage='net.internetisalie.lunar.luacats.lang.psi.impl'
    psiImplUtilClass='net.internetisalie.lunar.luacats.lang.psi.LuaPsiImplUtil'
}

// Root

root ::= comment
comment ::= commentLine*
private commentLine ::= DASHES (anyTag | typeOption | description)? { pin=1 }

// Meta

meta ArgName ::= <<child>>
meta ArgType ::= <<child>>
meta ArgValue ::= <<child>>
meta ArgKeyword ::= <<child>>
meta ArgSymbol ::= <<child>>

// Type Options

typeOption ::= '|' <<ArgValue (STRING | CODE | NUMBER | NAME)>> [ '#' description ]

/// Tags

private anyTag ::=
    aliasTag
    | asyncTag
    | castTag
    | classTag
    | deprecatedTag
    | diagnosticTag
    | enumTag
    | fieldTag
    | genericTag
    | metaTag
    | moduleTag
    | nodiscardTag
    | operatorTag
    | overloadTag
    | packageTag
    | paramTag
    | privateTag
    | protectedTag
    | returnTag
    | seeTag
    | sourceTag
    | typeTag
    | varargTag
    | versionTag

aliasTag ::= '@alias' <<ArgName NAME>> <<ArgType type>>? description?

asyncTag ::= '@async' description?

castTag ::= '@cast' <<ArgName castName>> <<ArgType castModifier>> { ',' <<ArgType castModifier>> }* description?
private castName ::= NAME
castModifier ::= addOrSubtract? type
addOrSubtract ::= '+' | '-'

classTag ::= '@class' <<ArgKeyword exactKeyword>>? <<ArgType typeName>> [':' parentTypes] description?
private exactKeyword ::= '(exact)'
parentTypes ::= <<ArgType parentType>> { ',' <<ArgType parentType>> }*
private typeName ::= parameterizedName | NAME
private parentType ::= type

deprecatedTag ::= '@deprecated' description?

diagnosticTag ::= '@diagnostic' <<ArgKeyword diagnosticState>> [<<ArgSymbol (':')>> diagnostics] description?
diagnosticState ::= 'disable-next-line' | 'disable-line' | 'disable' | 'enable'
diagnostics ::= <<ArgName diagnosticName>> {',' <<ArgName diagnosticName>>}*
private diagnosticName ::= NAME

enumTag ::= '@enum' <<ArgKeyword enumKey>>? <<ArgName enumName>> description?
private enumKey ::= '(key)'
private enumName ::= NAME

fieldTag ::= '@field' fieldDescriptor <<ArgType type>> description?
fieldDescriptor ::= (<<ArgKeyword fieldScope>>? <<ArgName fieldNameDescriptor>>)
    | (<<ArgKeyword fieldScope>>? <<ArgType fieldKeyDescriptor>>)
fieldScope ::= 'private' | 'protected' | 'public'
fieldNameDescriptor ::= NAME '?'?
fieldKeyDescriptor ::= '[' type ']'

genericTag ::= '@generic' genericTypeParams? description?
genericTypeParams ::= genericTypeParam { ',' genericTypeParam }*
genericTypeParam ::= <<ArgName typeParam>> ( <<ArgSymbol (':')>> <<ArgType parentType>> )?

metaTag ::= '@meta' <<ArgName metaName>>? description?
private metaName ::= NAME

moduleTag ::= '@module' <<ArgValue moduleName>> description?
private moduleName ::= STRING

nodiscardTag ::= '@nodiscard' description?

operatorTag ::= '@operator' operatorSignature description?
operatorSignature ::= <<ArgName operatorName>> [<<ArgSymbol ('(')>> <<ArgType operatorArgumentType>> <<ArgSymbol (')')>>] <<ArgSymbol (':')>> <<ArgType operatorReturnType>>
private operatorName ::= 'unm' | 'add' | 'sub' | 'mul' | 'div' | 'idiv' | 'mod' | 'pow' | 'concat' | 'len' | 'eq' | 'lt' | 'le' | 'call' | 'index' | 'newindex'
private operatorArgumentType ::= type
private operatorReturnType ::= type

overloadTag ::= '@overload' overloadFunctionSignature description?
overloadFunctionSignature ::=
    <<ArgKeyword ('fun')>>
    <<ArgSymbol ('(')>>
    functionSignatureArguments?
    <<ArgSymbol (')')>>
    functionSignatureReturnType?

packageTag ::= '@package' description?

paramTag ::= '@param' ((<<ArgName NAME>> <<ArgSymbol ('?')>>?) | <<ArgSymbol ('...')>>) <<ArgType type>> description?

privateTag ::= '@private' description?
protectedTag ::= '@protected' description?

returnTag ::= '@return' returnTypeDescriptor { ',' returnTypeDescriptor }*
returnTypeDescriptor ::= <<ArgType type>> [(<<ArgName NAME>>? '#' returnDescription? ) | ( <<ArgName NAME>> returnDescription ? ) | returnDescription]

seeTag ::= '@see' <<ArgName NAME>> description?

sourceTag ::= '@source' <<ArgValue STRING>> description?

typeTag ::= '@type' <<ArgType type>> description?

varargTag ::= '@vararg' <<ArgType type>> description?

versionTag ::= '@version' versionSpecs description?
versionSpecs ::= versionSpec { <<ArgSymbol (',')>> versionSpec }*
versionSpec ::= <<ArgSymbol versionComparison>>? <<ArgValue versionNumber>>
versionNumber ::= '5.1' | '5.2' | '5.3' | '5.4' | 'JIT'
versionComparison ::= '<' | '>'

/// Types

type ::= '(' unionType ')' | unionType
unionType ::= arrayType { '|' arrayType }*
arrayType ::= distinctType '[]'?
distinctType ::=
    tupleType
    | dictionaryType
    | literalTableType
    | functionSignatureType
    | parameterizedName
    | parameterName
    | literalType
    | simpleType

literalType ::= STRING | NUMBER
tupleType ::= '[' type { ',' type }* ']'
dictionaryType ::= '{' '[' type ']' ':' type '}'
literalTableType ::= '{' tableLiteralEntries? '}'
private tableLiteralEntries ::= tableLiteralEntry { ',' tableLiteralEntry }*
tableLiteralEntry ::= simpleType ':' type
functionSignatureType ::= 'fun' '(' functionSignatureArguments? ')' functionSignatureReturnType?
private functionSignatureArguments ::= functionSignatureArgument { ',' functionSignatureArgument }*
functionSignatureArgument ::= <<ArgName argumentName>> <<ArgSymbol (':')>> <<ArgType type>>
private argumentName ::= NAME
functionSignatureReturnType ::= <<ArgSymbol (':')>> <<ArgType type>>
parameterizedName ::= genericType '<' typeParam {',' typeParam }* '>'
genericType ::= NAME
typeParam ::= NAME
parameterName ::= CODE
private simpleType ::= builtinType | namedType
builtinType ::= 'nil' | 'any' | 'boolean' | 'string' | 'number' | 'integer' | 'function' | 'table' | 'thread' | 'userdata' | 'lightuserdata'
namedType ::= NAME

/// Explanatory Text

description ::= (NAME | NUMBER | STRING | SYMBOL | TEXT)+
returnDescription ::= (NAME | NUMBER | STRING | (!(',' returnTypeDescriptor) SYMBOL) | TEXT)+
