{
    // not used except for preview
    tokens = [
        WS     =   'regexp:[ \t\v\a]+'
        NUMBER =   'regexp:[0-9]+([.][0-9]+)?([Ee][+-]?[0-9]+)?'
        STRING =   'regexp:"[^"]*"'

        AND    = 'and'
        BREAK  = 'break'
        DO     = 'do'
        ELSE   = 'else'
        ELSEIF = 'elseif'
        END    = 'end'
        FALSE  = 'false'
        FOR    = 'for'
        FUNCTION = 'function'
        IF     = 'if'
        IN     = 'in'
        GOTO   = 'goto'
        LOCAL  = 'local'
        NIL    = 'nil'
        NOT    = 'not'
        OR     = 'or'
        REPEAT = 'repeat'
        RETURN = 'return'
        THEN   = 'then'
        TRUE   = 'true'
        UNTIL  = 'until'
        WHILE  = 'while'

        MARKER = '::'
        SHEBANG = '#!'
        CONCAT = '..'
        ELLIPSIS = '...'
        EQ     = '=='
        GE     = '>='
        LE     = '<='
        NE     = '~='
        PLUS   = '+'
        MINUS  = '-'
        MULT   = '*'
        DIV    = '/'
        INTDIV = '//'
        EXP    = '^'
        MOD    = '%'
        ASSIGN = '='
        GT     = '>'
        LT     = '<'
        LPAREN = '('
        RPAREN = ')'
        LBRACK = '['
        RBRACK = ']'
        LCURLY = '{'
        RCURLY = '}'
        GETN   = '#'
        COMMA  = ','
        SEMI   = ';'
        COLON  = ':'
        DOT    = '.'
        AMP    = '&'
        NEG    = '~'
        PIPE   = '|'
        BSR    = '>>'
        BSL    = '<<'
        LONGCOMMENT  = '--[[]]'
        SHORTCOMMENT  = '--'

        IDENTIFIER   =   'regexp:[_a-zA-Z][_a-zA-Z0-9]*'
    ]
//    generate=[tokenAccessors="no"]

    parserClass="net.internetisalie.lunar.lang.parser.LuaParser"
    parserImports=[]

    extends="net.internetisalie.lunar.lang.psi.LuaBaseElement"

    tokenTypeClass="net.internetisalie.lunar.lang.psi.LuaTokenType"

    elementTypeHolderClass="net.internetisalie.lunar.lang.psi.LuaElementTypes"
    elementTypeClass="net.internetisalie.lunar.lang.psi.LuaElementType"

    psiClassPrefix='Lua'
    psiPackage='net.internetisalie.lunar.lang.psi'
    psiImplPackage='net.internetisalie.lunar.lang.psi.impl'
    psiImplUtilClass='net.internetisalie.lunar.lang.psi.LuaPsiImplUtil'

    extends(".*Statement")=statement
    extends(".*Decl")=statement

//    consumeTokenMethod(".*_expr|expr")="consumeTokenFast"
}

root ::= block*

block ::= not_eof {statement}* [finalStatement SEMI?]
private not_eof ::= !<<eof>>

statement ::= emptyStatement
    | assignmentStatement
    | funcCallStatement
    | label
    | breakStatement
    | gotoStatement
    | doStatement
    | whileStatement
    | repeatStatement
    | ifStatement
    | numericForStatement
    | genericForStatement
    | funcDecl
    | localFuncDecl
    | localVarDecl
    { extends=statement }

emptyStatement ::= ';'
assignmentStatement ::= varList '=' exprList
funcCallStatement ::= funcCall
breakStatement ::= BREAK
gotoStatement ::= GOTO labelRef
doStatement ::= DO block END {
    implements = ["net.internetisalie.lunar.lang.psi.LuaBlockParent"]
    methods=[getBlockList]
}
whileStatement ::= WHILE expr DO block END {
    implements = ["net.internetisalie.lunar.lang.psi.LuaBlockParent"]
    methods=[getBlockList]
}
repeatStatement ::= REPEAT block UNTIL expr {
    implements = ["net.internetisalie.lunar.lang.psi.LuaBlockParent"]
    methods=[getBlockList]
}
ifStatement ::= IF expr THEN block {ELSEIF expr THEN block}* [ELSE block] END {
    implements = ["net.internetisalie.lunar.lang.psi.LuaBlockParent"]
}
numericForStatement ::= FOR IDENTIFIER '=' expr ',' expr [',' expr] DO block END {
    implements = ["net.internetisalie.lunar.lang.psi.LuaBlockParent"]
    methods=[getBlockList]
}
genericForStatement ::= FOR nameList IN exprList DO block END {
    implements = ["net.internetisalie.lunar.lang.psi.LuaBlockParent"]
    methods=[getBlockList]
}
finalStatement ::= RETURN [exprList] [';']
label ::= '::' labelName '::' { extends=statement }
funcName ::= nameRef funcNameProperty* funcNameMethod?
funcNameProperty ::= '.' nameRef
funcNameMethod ::= ':' nameRef
varList ::= var {',' var}*
nameList ::= nameRef {',' nameRef}*
nameRef ::= IDENTIFIER {
    mixin="net.internetisalie.lunar.lang.psi.LuaNameRefBaseImpl"
    implements="net.internetisalie.lunar.lang.psi.LuaNameRefElement"
}

exprList ::= expr {',' expr}*

localFuncDecl ::= LOCAL FUNCTION nameRef funcBody {
    implements = [
        "net.internetisalie.lunar.lang.psi.LuaCommentOwner"
        "net.internetisalie.lunar.lang.psi.LuaBlockParent"
    ]
    methods=[
        getComment getDocComment getCatsComment
        getBlockList
    ]
    extends=statement
}

funcDecl ::= FUNCTION funcName funcBody {
    implements = [
        "net.internetisalie.lunar.lang.psi.LuaCommentOwner"
        "net.internetisalie.lunar.lang.psi.LuaBlockParent"
    ]
    methods=[
        getComment getDocComment getCatsComment
        getBlockList
    ]
    extends=statement
}

localVarDecl ::= LOCAL nameList ['=' exprList] {
    implements = [
        "net.internetisalie.lunar.lang.psi.LuaCommentOwner"
    ]
    methods=[
        getComment getDocComment getCatsComment
    ]
    extends=statement
}

labelRef ::= IDENTIFIER {
    mixin="net.internetisalie.lunar.lang.psi.LuaLabelRefBaseImpl"
    implements="net.internetisalie.lunar.lang.psi.LuaNameRefElement"
}
labelName ::= IDENTIFIER {
    mixin="net.internetisalie.lunar.lang.psi.LuaNameDeclElementImpl"
    implements="net.internetisalie.lunar.lang.psi.LuaNameDeclElement"
}

expr ::= terminalExpr
    | funcDef
    | prefixExpr
    | tableConstructor
    | orBinOpExpr
    | andBinOpExpr
    | relBinOpExpr
    | borBinOpExpr
    | bnotBinOpExpr
    | bandBinOpExpr
    | bshiftBinOpExpr
    | concatBinOpExpr
    | addBinOpExpr
    | mulBinOpExpr
    | unOpExpr
    | expBinOpExpr
    {extends=expr}

terminalExpr ::= NIL | FALSE | TRUE | NUMBER | STRING | ELLIPSIS { extends=expr }
orBinOpExpr ::= expr <<binOps 'or'>> expr { extends=binOpExpr elementType=binOpExpr }
andBinOpExpr ::= expr <<binOps 'and'>> expr { extends=binOpExpr elementType=binOpExpr }
relBinOpExpr ::= expr <<binOps ('=='|'~='|'<'|'<='|'>='|'>')>> expr { extends=binOpExpr elementType=binOpExpr }
borBinOpExpr ::= expr <<binOps '|'>> expr { extends=binOpExpr elementType=binOpExpr }
bnotBinOpExpr ::= expr <<binOps '~'>> expr { extends=binOpExpr elementType=binOpExpr }
bandBinOpExpr ::= expr <<binOps '&'>> expr { extends=binOpExpr elementType=binOpExpr }
bshiftBinOpExpr ::= expr <<binOps ('<<'|'>>')>> expr { extends=binOpExpr elementType=binOpExpr }
addBinOpExpr ::= expr <<binOps ('+'|'-')>> expr { extends=binOpExpr elementType=binOpExpr }
mulBinOpExpr ::= expr <<binOps ('*'|'/'|'//'|'%')>> expr { extends=binOpExpr elementType=binOpExpr }
concatBinOpExpr ::= expr <<binOps '..'>> expr { rightAssociative=true extends=binOpExpr elementType=binOpExpr }
unOpExpr ::= unOp expr { methods=[right="/expr"] extends=expr }
expBinOpExpr ::= expr <<binOps '^'>> expr { rightAssociative=true extends=binOpExpr elementType=binOpExpr }

meta binOps ::= <<choices>> {elementType=binOp}
fake binOpExpr ::= expr binOp expr { methods=[ left="/expr[0]" right="/expr[1]" ] extends=expr }

var ::= nameRef varSuffix*
    | '(' expr ')' varSuffix+
varSuffix ::= nameAndArgs* indexExpr

prefixExpr ::= varOrExp nameAndArgs* {extends=expr}
funcCall ::= varOrExp nameAndArgs+
varOrExp ::= var | '(' expr ')'
nameAndArgs ::= methodExpr? args
methodExpr ::= ':' nameRef
indexExpr ::= ('[' expr ']') | ('.' nameRef)

args ::=  '(' [exprList] ')' | tableConstructor | STRING

funcDef ::= FUNCTION funcBody {
    extends="expr"
    implements="net.internetisalie.lunar.lang.psi.LuaBlockParent"
    methods=[getBlockList]
}

private funcBody ::= '(' [parList] ')' block END

parList ::= nameList [',' '...'] | '...'

tableConstructor ::= '{' [fieldList] '}' {extends=expr}

fieldList ::= field {fieldSep field}* [fieldSep]

field ::= '[' expr ']' '=' expr | IDENTIFIER '=' expr | expr

fieldSep ::= ',' | ';'

binOp ::=  '+' | '-' | '*' | '/' | '//' | '^' | '%' |
    '&' | '~' | '|' | '>>' | '<<' | '..' |
    '<' | '<=' | '>' | '>=' | '==' | '~=' |
    AND | OR

unOp ::= '-' | NOT | '#' | '~'
