{
    // not used except for preview
    tokens = [
        WS     =   'regexp:[ \t\v\a]+'
        NUMBER =   'regexp:[0-9]+([.][0-9]+)?([Ee][+-]?[0-9]+)?'
        STRING =   'regexp:"[^"]*"'

        AND    = 'and'
        BREAK  = 'break'
        DO     = 'do'
        ELSE   = 'else'
        ELSEIF = 'elseif'
        END    = 'end'
        FALSE  = 'false'
        FOR    = 'for'
        FUNCTION = 'function'
        IF     = 'if'
        IN     = 'in'
        GOTO   = 'goto'
        LOCAL  = 'local'
        NIL    = 'nil'
        NOT    = 'not'
        OR     = 'or'
        REPEAT = 'repeat'
        RETURN = 'return'
        THEN   = 'then'
        TRUE   = 'true'
        UNTIL  = 'until'
        WHILE  = 'while'

        MARKER = '::'
        SHEBANG = '#!'
        CONCAT = '..'
        ELLIPSIS = '...'
        EQ     = '=='
        GE     = '>='
        LE     = '<='
        NE     = '~='
        PLUS   = '+'
        MINUS  = '-'
        MULT   = '*'
        DIV    = '/'
        INTDIV = '//'
        EXP    = '^'
        MOD    = '%'
        ASSIGN = '='
        GT     = '>'
        LT     = '<'
        LPAREN = '('
        RPAREN = ')'
        LBRACK = '['
        RBRACK = ']'
        LCURLY = '{'
        RCURLY = '}'
        GETN   = '#'
        COMMA  = ','
        SEMI   = ';'
        COLON  = ':'
        DOT    = '.'
        AMP    = '&'
        NEG    = '~'
        PIPE   = '|'
        BSR    = '>>'
        BSL    = '<<'
        LONGCOMMENT  = '--[[]]'
        SHORTCOMMENT  = '--'

        IDENTIFIER   =   'regexp:[_a-zA-Z][_a-zA-Z0-9]*'
    ]
//    generate=[tokenAccessors="no"]

    parserClass="net.internetisalie.lunar.lang.parser.LuaParser"
    parserImports=[]

    extends="net.internetisalie.lunar.lang.psi.LuaBaseElement"

    tokenTypeClass="net.internetisalie.lunar.lang.psi.LuaTokenType"

    elementTypeHolderClass="net.internetisalie.lunar.lang.psi.LuaElementTypes"
    elementTypeClass="net.internetisalie.lunar.lang.psi.LuaElementType"

    psiClassPrefix='Lua'
    psiPackage='net.internetisalie.lunar.lang.psi'
    psiImplPackage='net.internetisalie.lunar.lang.psi.impl'
    psiImplUtilClass='net.internetisalie.lunar.lang.psi.LuaPsiImplUtil'
}

// https://parrot.github.io/parrot-docs0/0.4.7/html/languages/lua/doc/lua51.bnf.html

root ::= block*
block ::= not_eof {statement SEMI?}* [finalStatement SEMI?]
private not_eof ::= !<<eof>>

statement ::= assignmentStatement
    | funcCall
    | label
    | BREAK
    | gotoStatement
    | doStatement
    | whileStatement
    | repeatStatement
    | ifStatement
    | numericForStatement
    | genericForStatement
    | funcDecl
    | localFuncDecl
    | localVarDecl
assignmentStatement ::= varList '=' exprList
gotoStatement ::= GOTO labelRef
doStatement ::= DO block END
whileStatement ::= WHILE expr DO block END
repeatStatement ::= REPEAT block UNTIL expr
ifStatement ::= IF expr THEN block {ELSEIF expr THEN block}* [ELSE block] END
numericForStatement ::= FOR IDENTIFIER '=' expr ',' expr [',' expr] DO block END
genericForStatement ::= FOR nameList IN exprList DO block END
finalStatement ::= RETURN [exprList] [';']
label ::= '::' labelName '::'
funcName ::= nameRef funcNameProperty* funcNameMethod?
funcNameProperty ::= '.' nameRef
funcNameMethod ::= ':' nameRef
varList ::= var {',' var}*
nameList ::= nameRef {',' nameRef}*
nameRef ::= IDENTIFIER {
    mixin="net.internetisalie.lunar.lang.psi.LuaNameRefBaseImpl"
    implements="net.internetisalie.lunar.lang.psi.LuaNameRefElement"
}

exprList ::= expr {',' expr}*

localFuncDecl ::= LOCAL FUNCTION nameRef funcBody {
    implements = [
        "net.internetisalie.lunar.lang.psi.LuaCommentOwner"
    ]
    methods=[getComment getDocComment getCatsComment]
}

funcDecl ::= FUNCTION funcName funcBody {
    implements = [
        "net.internetisalie.lunar.lang.psi.LuaCommentOwner"
    ]
    methods=[getComment getDocComment getCatsComment]
}

localVarDecl ::= LOCAL nameList ['=' exprList]

labelRef ::= IDENTIFIER {
    mixin="net.internetisalie.lunar.lang.psi.LuaLabelRefBaseImpl"
    implements="net.internetisalie.lunar.lang.psi.LuaNameRefElement"
}
labelName ::= IDENTIFIER {
    mixin="net.internetisalie.lunar.lang.psi.LuaNameDeclElementImpl"
    implements="net.internetisalie.lunar.lang.psi.LuaNameDeclElement"
}

// TODO
// http://lua-users.org/wiki/LpegRecipes - Lua Parser (batrick)
//  -- Let's come up with a syntax that does not use left recursion
//  -- (only listing changes to Lua 5.1 extended BNF syntax)
//  -- value ::= nil | false | true | Number | String | '...' | function |
//  --           tableconstructor | functioncall | var | '(' exp ')'
//  -- exp ::= unop exp | value [binop exp]
//  -- prefix ::= '(' exp ')' | Name
//  -- index ::= '[' exp ']' | '.' Name
//  -- call ::= args | ':' Name args
//  -- suffix ::= call | index
//  -- var ::= prefix {suffix} index | Name
//  -- functioncall ::= prefix {suffix} call

// use right-recursion for expressions
expr ::= (NIL | FALSE | TRUE | NUMBER | STRING | ELLIPSIS | funcDef | prefixExpr | tableConstructor | unOp expr) {binOp expr}*

var ::= nameRef varSuffix*
    | '(' expr ')' varSuffix+
varSuffix ::= nameAndArgs* indexExpr

prefixExpr ::= varOrExp nameAndArgs*
funcCall ::= varOrExp nameAndArgs+
varOrExp ::= var | '(' expr ')'
nameAndArgs ::= methodExpr? args
methodExpr ::= ':' nameRef
indexExpr ::= ('[' expr ']') | ('.' nameRef)

args ::=  '(' [exprList] ')' | tableConstructor | STRING

funcDef ::= FUNCTION funcBody

private funcBody ::= '(' [parList] ')' block END

parList ::= nameList [',' '...'] | '...'

tableConstructor ::= '{' [fieldList] '}'

fieldList ::= field {fieldSep field}* [fieldSep]

field ::= '[' expr ']' '=' expr | IDENTIFIER '=' expr | expr

fieldSep ::= ',' | ';'

binOp ::=  '+' | '-' | '*' | '/' | '//' | '^' | '%' |
    '&' | '~' | '|' | '>>' | '<<' | '..' |
    '<' | '<=' | '>' | '>=' | '==' | '~=' |
    AND | OR

unOp ::= '-' | NOT | '#' | '~'
