#!/usr/bin/env python3
"""Generate docs/status.md from documentation front-matter.

With the Saga tracker retired, the docs are the source of truth. This rolls up
per-epic feature completion from each doc's `status` field.

Usage:
    python3 scripts/gen_status.py            # regenerate docs/status.md
    python3 scripts/gen_status.py --check    # exit 1 if status.md is stale
"""
import os
import sys

try:
    import yaml
except ImportError:
    sys.exit("gen_status: PyYAML is required (pip install pyyaml)")

FEATURES = "docs/features"
STATUS_MD = "docs/status.md"
STATUSES = ["done", "in_progress", "planned", "todo", "blocked", "cancelled"]
PRIORITY_DOT = {"critical": "🔴", "high": "🔴", "medium": "🟡", "low": "🟢"}
STATUS_DOT = {"done": "✅", "in_progress": "🔵", "planned": "⚪",
              "todo": "⚫", "blocked": "🟠", "cancelled": "🚫"}
# Completion counts only an epic's DIRECT children that are work items
# (features/stories/tasks) — not nested descendants, not design/plan/qa/risk artifacts.
WORK_ITEM_TYPES = {"feature", "user-story", "task"}


def frontmatter(path):
    with open(path, encoding="utf-8") as fh:
        text = fh.read()
    if not text.startswith("---"):
        return {}
    parts = text.split("---", 2)
    if len(parts) < 3:
        return {}
    try:
        data = yaml.safe_load(parts[1])
    except yaml.YAMLError:
        return {}
    return data if isinstance(data, dict) else {}


def epics():
    found = []
    for name in sorted(os.listdir(FEATURES)):
        path = os.path.join(FEATURES, name)
        if os.path.isdir(path):
            req = os.path.join(path, "requirements.md")
            fm = frontmatter(req) if os.path.isfile(req) else {}
            if fm.get("type") == "epic":
                found.append((fm, path))
        elif name.endswith(".md"):
            fm = frontmatter(path)
            if fm.get("type") == "epic":
                found.append((fm, None))
    return found


def all_items():
    items = []
    for root, _dirs, files in os.walk(FEATURES):
        for fn in files:
            if fn.endswith(".md"):
                fm = frontmatter(os.path.join(root, fn))
                if str(fm.get("id", "")).strip():
                    items.append(fm)
    return items


def bar(pct):
    filled = round(pct / 10)
    return "█" * filled + "░" * (10 - filled)


def render():
    children = {}
    for it in all_items():
        parent = str(it.get("parent_id", "")).strip()
        if parent:
            children.setdefault(parent, []).append(it)

    rows, g_done, g_total = [], 0, 0
    for fm, _dirpath in epics():
        kids = [c for c in children.get(fm.get("id"), [])
                if c.get("type") in WORK_ITEM_TYPES]
        total = len(kids)
        done = sum(1 for c in kids if c.get("status") == "done")
        pct = (done * 100 // total) if total else (100 if fm.get("status") == "done" else 0)
        rows.append({
            "id": fm.get("id", "?"), "title": fm.get("title", fm.get("id", "?")),
            "priority": fm.get("priority", "—"), "status": fm.get("status", "—"),
            "done": done, "total": total, "pct": pct,
        })
        g_done += done
        g_total += total
    rows.sort(key=lambda r: (-r["pct"], r["id"]))
    g_pct = (g_done * 100 // g_total) if g_total else 0

    out = [
        "---", 'id: "STATUS"', 'title: "Project Status"', 'type: "spec"',
        'status: "done"', 'priority: "medium"', "folders:", '  - "[[features]]"', "---",
        "# Lunar Project Status Report", "",
        "<!-- GENERATED by scripts/gen_status.py from documentation front-matter.",
        "     The Saga tracker is retired; the docs are the source of truth.",
        "     Do not edit by hand — run `python3 scripts/gen_status.py`. -->", "",
        f"**Completion: {g_pct}%** ({g_done} of {g_total} work items `done`)", "",
        "## Progress by Epic", "",
        "| Epic | Priority | Epic status | Work items done | Completion |",
        "| :--- | :--- | :--- | :--- | :--- |",
    ]
    for r in rows:
        prio = f"{PRIORITY_DOT.get(r['priority'], '⚪')} {r['priority']}"
        stat = f"{STATUS_DOT.get(r['status'], '')} {r['status']}".strip()
        out.append(f"| **{r['id']}** | {prio} | {stat} | "
                   f"{r['done']}/{r['total']} | {bar(r['pct'])} {r['pct']}% |")
    out += [
        "", "## Notes", "",
        "- Completion counts an epic's **direct work-item children** (`feature`/`user-story`/",
        "  `task`) marked `done` — not nested descendants, not design/plan/qa/risk artifacts.",
        "  Derived from front-matter (the Saga tracker is retired).",
        "- Status vocabulary: `todo` (not defined) · `planned` (ready to execute) ·",
        "  `in_progress` · `done` · `cancelled`.",
        "- Regenerate with `python3 scripts/gen_status.py` (CI runs `--check`).", "",
    ]
    return "\n".join(out) + "\n"


def main():
    if not os.path.isdir(FEATURES):
        sys.exit(f"gen_status: '{FEATURES}' not found")
    content = render()
    if "--check" in sys.argv[1:]:
        current = open(STATUS_MD, encoding="utf-8").read() if os.path.isfile(STATUS_MD) else ""
        if current != content:
            sys.exit(f"gen_status: {STATUS_MD} is stale; run `python3 scripts/gen_status.py`")
        print(f"gen_status: {STATUS_MD} is up to date")
    else:
        with open(STATUS_MD, "w", encoding="utf-8") as fh:
            fh.write(content)
        print(f"gen_status: wrote {STATUS_MD}")


if __name__ == "__main__":
    main()
